/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion.vista;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Usuario
 */
public class AgregarAdmin extends javax.swing.JPanel {

    /**
     * Creates new form AgregarAdmin
     */
    public AgregarAdmin() {
        initComponents();
        
        OcultarPanels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAccion = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblMessage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        listaEntidades = new javax.swing.JComboBox<>();
        AggVcls = new javax.swing.JPanel();
        lblNumSerie = new javax.swing.JLabel();
        txtNumSerie = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblPaisP = new javax.swing.JLabel();
        txtPaisP = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lblVersion = new javax.swing.JLabel();
        txtVersion = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        lblModelo = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        lblColor = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        btnAgregarVcl = new javax.swing.JButton();
        lblStock = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jSeparator56 = new javax.swing.JSeparator();
        AggVrs = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        lblNombre = new javax.swing.JLabel();
        txtNombreVrs = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        lblTransmision = new javax.swing.JLabel();
        txtTransmision = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        lblMotorMt = new javax.swing.JLabel();
        txtMotorMt = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        btnAgregarVrs = new javax.swing.JButton();
        AggModelos = new javax.swing.JPanel();
        lblIdMdl = new javax.swing.JLabel();
        txtIdModelo = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        lblNombreMdl = new javax.swing.JLabel();
        txtNombreMod = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        btnAgregarMdl = new javax.swing.JButton();
        AggColors = new javax.swing.JPanel();
        btnAgregarClr = new javax.swing.JButton();
        lblIdClr = new javax.swing.JLabel();
        txtIdColor = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        lblNombreClr = new javax.swing.JLabel();
        txtNombreClr = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        AggEmp = new javax.swing.JPanel();
        lblIdEmp = new javax.swing.JLabel();
        txtIdEmp = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        lblNombreEmp = new javax.swing.JLabel();
        txtNombreEmp = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        lblApellEmp = new javax.swing.JLabel();
        txtApellEmp = new javax.swing.JTextField();
        jSeparator20 = new javax.swing.JSeparator();
        lblVersion1 = new javax.swing.JLabel();
        txtUserEmp = new javax.swing.JTextField();
        jSeparator21 = new javax.swing.JSeparator();
        lblMotor2 = new javax.swing.JLabel();
        txtContrEmp = new javax.swing.JTextField();
        jSeparator22 = new javax.swing.JSeparator();
        lblTrans2 = new javax.swing.JLabel();
        txtComiEmp = new javax.swing.JTextField();
        jSeparator23 = new javax.swing.JSeparator();
        lblModelo1 = new javax.swing.JLabel();
        txtNSSEmp = new javax.swing.JTextField();
        jSeparator24 = new javax.swing.JSeparator();
        lblColor1 = new javax.swing.JLabel();
        txtTelefEmp = new javax.swing.JTextField();
        jSeparator25 = new javax.swing.JSeparator();
        btnAggEmp = new javax.swing.JButton();
        lblColor2 = new javax.swing.JLabel();
        txtCorreoEmp = new javax.swing.JTextField();
        jSeparator26 = new javax.swing.JSeparator();
        AggDept = new javax.swing.JPanel();
        lblIdDept = new javax.swing.JLabel();
        txtIdDept = new javax.swing.JTextField();
        jSeparator27 = new javax.swing.JSeparator();
        lblNombreDept = new javax.swing.JLabel();
        txtNombreDept = new javax.swing.JTextField();
        jSeparator28 = new javax.swing.JSeparator();
        btnAggDept = new javax.swing.JButton();
        AggDirEmp = new javax.swing.JPanel();
        lblIdDirEmp = new javax.swing.JLabel();
        txtIdDirEmp = new javax.swing.JTextField();
        jSeparator29 = new javax.swing.JSeparator();
        lblCalleDirEmp = new javax.swing.JLabel();
        txtCalleDirEmp = new javax.swing.JTextField();
        jSeparator30 = new javax.swing.JSeparator();
        lblColoniaDirEmp = new javax.swing.JLabel();
        txtColoniaDirEmp = new javax.swing.JTextField();
        jSeparator31 = new javax.swing.JSeparator();
        lblNumExtDE = new javax.swing.JLabel();
        txtNExtDirEmp = new javax.swing.JTextField();
        jSeparator32 = new javax.swing.JSeparator();
        btnAggDirEmp = new javax.swing.JButton();
        lblMotor4 = new javax.swing.JLabel();
        txtCPEmp = new javax.swing.JTextField();
        jSeparator33 = new javax.swing.JSeparator();
        AggCotiz = new javax.swing.JPanel();
        lblId5 = new javax.swing.JLabel();
        txtId2 = new javax.swing.JTextField();
        jSeparator34 = new javax.swing.JSeparator();
        lblNombre5 = new javax.swing.JLabel();
        txtPrecio4 = new javax.swing.JTextField();
        jSeparator35 = new javax.swing.JSeparator();
        lblTrans4 = new javax.swing.JLabel();
        txtTrans4 = new javax.swing.JTextField();
        jSeparator36 = new javax.swing.JSeparator();
        lblMotor5 = new javax.swing.JLabel();
        txtMotor5 = new javax.swing.JTextField();
        jSeparator37 = new javax.swing.JSeparator();
        btnAggCot = new javax.swing.JButton();
        lblMotor6 = new javax.swing.JLabel();
        txtMotor6 = new javax.swing.JTextField();
        jSeparator38 = new javax.swing.JSeparator();
        AggFacts = new javax.swing.JPanel();
        lblId6 = new javax.swing.JLabel();
        txtId3 = new javax.swing.JTextField();
        jSeparator39 = new javax.swing.JSeparator();
        lblNombre6 = new javax.swing.JLabel();
        txtPrecio5 = new javax.swing.JTextField();
        jSeparator40 = new javax.swing.JSeparator();
        lblTrans5 = new javax.swing.JLabel();
        txtTrans5 = new javax.swing.JTextField();
        jSeparator41 = new javax.swing.JSeparator();
        btnAggFact = new javax.swing.JButton();
        AggCli = new javax.swing.JPanel();
        lblNumSerie2 = new javax.swing.JLabel();
        txtNumSerie2 = new javax.swing.JTextField();
        jSeparator42 = new javax.swing.JSeparator();
        lblPrecio2 = new javax.swing.JLabel();
        txtPrecio6 = new javax.swing.JTextField();
        jSeparator43 = new javax.swing.JSeparator();
        lblPaisP2 = new javax.swing.JLabel();
        txtPaisP2 = new javax.swing.JTextField();
        jSeparator44 = new javax.swing.JSeparator();
        lblVersion2 = new javax.swing.JLabel();
        txtVersion2 = new javax.swing.JTextField();
        jSeparator45 = new javax.swing.JSeparator();
        lblMotor7 = new javax.swing.JLabel();
        txtMotor7 = new javax.swing.JTextField();
        jSeparator46 = new javax.swing.JSeparator();
        lblTrans6 = new javax.swing.JLabel();
        txtTrans6 = new javax.swing.JTextField();
        jSeparator47 = new javax.swing.JSeparator();
        lblModelo2 = new javax.swing.JLabel();
        txtModelo2 = new javax.swing.JTextField();
        jSeparator48 = new javax.swing.JSeparator();
        lblColor3 = new javax.swing.JLabel();
        txtColor3 = new javax.swing.JTextField();
        jSeparator49 = new javax.swing.JSeparator();
        btnAggCli = new javax.swing.JButton();
        lblColor4 = new javax.swing.JLabel();
        txtColor4 = new javax.swing.JTextField();
        jSeparator50 = new javax.swing.JSeparator();
        AggDirCli = new javax.swing.JPanel();
        lblId7 = new javax.swing.JLabel();
        txtId4 = new javax.swing.JTextField();
        jSeparator51 = new javax.swing.JSeparator();
        lblNombre7 = new javax.swing.JLabel();
        txtPrecio7 = new javax.swing.JTextField();
        jSeparator52 = new javax.swing.JSeparator();
        lblTrans7 = new javax.swing.JLabel();
        txtTrans7 = new javax.swing.JTextField();
        jSeparator53 = new javax.swing.JSeparator();
        lblMotor8 = new javax.swing.JLabel();
        txtMotor8 = new javax.swing.JTextField();
        jSeparator54 = new javax.swing.JSeparator();
        btnAggDirCli = new javax.swing.JButton();
        lblMotor9 = new javax.swing.JLabel();
        txtMotor9 = new javax.swing.JTextField();
        jSeparator55 = new javax.swing.JSeparator();
        lblInstruct = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 470));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAccion.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblAccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccion.setText("Agregar");
        jPanel1.add(lblAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 200, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 10, 470));

        lblMessage.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(0, 193, 75));
        jPanel1.add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 450, 20));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administrador de base de datos");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 260, 30));

        listaEntidades.setBackground(new java.awt.Color(214, 5, 5));
        listaEntidades.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        listaEntidades.setForeground(new java.awt.Color(255, 255, 255));
        listaEntidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vehículos", "Versiones", "Modelos", "Colores", "Empleados", "Departamentos", "DireccionesEmpleados", "Cotizaciones", "Facturas", "Clientes", "DireccionesClientes" }));
        listaEntidades.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(listaEntidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 170, 40));

        AggVcls.setBackground(new java.awt.Color(255, 255, 255));
        AggVcls.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNumSerie.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNumSerie.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumSerie.setText("Número de serie:");
        AggVcls.add(lblNumSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 30));

        txtNumSerie.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNumSerie.setBorder(null);
        AggVcls.add(txtNumSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 240, 30));
        AggVcls.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 260, 10));

        lblPrecio.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblPrecio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPrecio.setText("Precio:");
        AggVcls.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, 30));

        txtPrecio.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtPrecio.setBorder(null);
        AggVcls.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 240, 30));
        AggVcls.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 260, 10));

        lblPaisP.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblPaisP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPaisP.setText("País de procedencia:");
        AggVcls.add(lblPaisP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 120, 30));

        txtPaisP.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtPaisP.setBorder(null);
        AggVcls.add(txtPaisP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 240, 30));
        AggVcls.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 260, 10));

        lblVersion.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblVersion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVersion.setText("Id Versión:");
        AggVcls.add(lblVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 100, 30));

        txtVersion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtVersion.setBorder(null);
        AggVcls.add(txtVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 240, 30));
        AggVcls.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 260, 10));

        lblModelo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblModelo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblModelo.setText("Id Modelo:");
        AggVcls.add(lblModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 80, 30));

        txtModelo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtModelo.setBorder(null);
        AggVcls.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 240, 30));
        AggVcls.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 260, 10));

        lblColor.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblColor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblColor.setText("Id Color:");
        AggVcls.add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 60, 30));

        txtColor.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtColor.setBorder(null);
        AggVcls.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 240, 30));
        AggVcls.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 260, 10));

        btnAgregarVcl.setBackground(new java.awt.Color(214, 5, 5));
        btnAgregarVcl.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAgregarVcl.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarVcl.setText("Agregar");
        AggVcls.add(btnAgregarVcl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 90, 30));

        lblStock.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblStock.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStock.setText("Stock:");
        AggVcls.add(lblStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 100, 30));

        txtStock.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtStock.setBorder(null);
        AggVcls.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 240, 30));
        AggVcls.add(jSeparator56, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 260, 10));

        jPanel1.add(AggVcls, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 320));

        AggVrs.setBackground(new java.awt.Color(255, 255, 255));
        AggVrs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblId.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblId.setText("Id:");
        AggVrs.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 30));

        txtId.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtId.setBorder(null);
        AggVrs.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 240, 30));
        AggVrs.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 260, 10));

        lblNombre.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre.setText("Nombre:");
        AggVrs.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 100, 30));

        txtNombreVrs.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNombreVrs.setBorder(null);
        AggVrs.add(txtNombreVrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 240, 30));
        AggVrs.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 260, 10));

        lblTransmision.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTransmision.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTransmision.setText("Transmisión:");
        AggVrs.add(lblTransmision, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 120, 30));

        txtTransmision.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtTransmision.setBorder(null);
        AggVrs.add(txtTransmision, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 240, 30));
        AggVrs.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 260, 10));

        lblMotorMt.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblMotorMt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMotorMt.setText("Motor:");
        AggVrs.add(lblMotorMt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 100, 30));

        txtMotorMt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtMotorMt.setBorder(null);
        AggVrs.add(txtMotorMt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 240, 30));
        AggVrs.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 260, 10));

        btnAgregarVrs.setBackground(new java.awt.Color(214, 5, 5));
        btnAgregarVrs.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAgregarVrs.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarVrs.setText("Agregar");
        AggVrs.add(btnAgregarVrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 90, 30));

        jPanel1.add(AggVrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 320));

        AggModelos.setBackground(new java.awt.Color(255, 255, 255));
        AggModelos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIdMdl.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblIdMdl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdMdl.setText("Id:");
        AggModelos.add(lblIdMdl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 110, 30));

        txtIdModelo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtIdModelo.setBorder(null);
        AggModelos.add(txtIdModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 240, 30));
        AggModelos.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 260, 10));

        lblNombreMdl.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNombreMdl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreMdl.setText("Nombre:");
        AggModelos.add(lblNombreMdl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 100, 30));

        txtNombreMod.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNombreMod.setBorder(null);
        AggModelos.add(txtNombreMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 240, 30));
        AggModelos.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 260, 10));

        btnAgregarMdl.setBackground(new java.awt.Color(214, 5, 5));
        btnAgregarMdl.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAgregarMdl.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarMdl.setText("Agregar");
        AggModelos.add(btnAgregarMdl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 90, 30));

        jPanel1.add(AggModelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 320));

        AggColors.setBackground(new java.awt.Color(255, 255, 255));
        AggColors.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregarClr.setBackground(new java.awt.Color(214, 5, 5));
        btnAgregarClr.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAgregarClr.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarClr.setText("Agregar");
        AggColors.add(btnAgregarClr, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 90, 30));

        lblIdClr.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblIdClr.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdClr.setText("Id:");
        AggColors.add(lblIdClr, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 110, 30));

        txtIdColor.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtIdColor.setBorder(null);
        AggColors.add(txtIdColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 240, 30));
        AggColors.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 260, 10));

        lblNombreClr.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNombreClr.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreClr.setText("Nombre:");
        AggColors.add(lblNombreClr, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 100, 30));

        txtNombreClr.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNombreClr.setBorder(null);
        AggColors.add(txtNombreClr, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 240, 30));
        AggColors.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 260, 10));

        jPanel1.add(AggColors, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 320));

        AggEmp.setBackground(new java.awt.Color(255, 255, 255));
        AggEmp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIdEmp.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblIdEmp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdEmp.setText("Id del empleado:");
        AggEmp.add(lblIdEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 30));

        txtIdEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtIdEmp.setBorder(null);
        AggEmp.add(txtIdEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 240, 30));
        AggEmp.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 260, 10));

        lblNombreEmp.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNombreEmp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreEmp.setText("Nombre:");
        AggEmp.add(lblNombreEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, 30));

        txtNombreEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNombreEmp.setBorder(null);
        AggEmp.add(txtNombreEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 240, 30));
        AggEmp.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 260, 10));

        lblApellEmp.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblApellEmp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblApellEmp.setText("Apellidos:");
        AggEmp.add(lblApellEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 120, 30));

        txtApellEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtApellEmp.setBorder(null);
        AggEmp.add(txtApellEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 240, 30));
        AggEmp.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 260, 10));

        lblVersion1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblVersion1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVersion1.setText("Usuario:");
        AggEmp.add(lblVersion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 100, 30));

        txtUserEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtUserEmp.setBorder(null);
        AggEmp.add(txtUserEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 240, 30));
        AggEmp.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 260, 10));

        lblMotor2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblMotor2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMotor2.setText("Contraseña:");
        AggEmp.add(lblMotor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 100, 30));

        txtContrEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtContrEmp.setBorder(null);
        AggEmp.add(txtContrEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 240, 30));
        AggEmp.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 260, 10));

        lblTrans2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTrans2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTrans2.setText("Comisión:");
        AggEmp.add(lblTrans2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 100, 30));

        txtComiEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtComiEmp.setBorder(null);
        AggEmp.add(txtComiEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 240, 30));
        AggEmp.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 260, 10));

        lblModelo1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblModelo1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblModelo1.setText("NSS:");
        AggEmp.add(lblModelo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 60, 30));

        txtNSSEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNSSEmp.setBorder(null);
        AggEmp.add(txtNSSEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 140, 30));
        AggEmp.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 160, 10));

        lblColor1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblColor1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblColor1.setText("Teléfono:");
        AggEmp.add(lblColor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 60, 30));

        txtTelefEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtTelefEmp.setBorder(null);
        AggEmp.add(txtTelefEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 140, 30));
        AggEmp.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 160, 10));

        btnAggEmp.setBackground(new java.awt.Color(214, 5, 5));
        btnAggEmp.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAggEmp.setForeground(new java.awt.Color(255, 255, 255));
        btnAggEmp.setText("Agregar");
        AggEmp.add(btnAggEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 90, 30));

        lblColor2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblColor2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblColor2.setText("Correo:");
        AggEmp.add(lblColor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 100, 30));

        txtCorreoEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCorreoEmp.setBorder(null);
        AggEmp.add(txtCorreoEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 220, 30));
        AggEmp.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 240, 10));

        jPanel1.add(AggEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 320));

        AggDept.setBackground(new java.awt.Color(255, 255, 255));
        AggDept.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIdDept.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblIdDept.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdDept.setText("Id del Departamento:");
        AggDept.add(lblIdDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 120, 30));

        txtIdDept.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtIdDept.setBorder(null);
        AggDept.add(txtIdDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 240, 30));
        AggDept.add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 260, 10));

        lblNombreDept.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNombreDept.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreDept.setText("Nombre:");
        AggDept.add(lblNombreDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 100, 30));

        txtNombreDept.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNombreDept.setBorder(null);
        AggDept.add(txtNombreDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 240, 30));
        AggDept.add(jSeparator28, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 260, 10));

        btnAggDept.setBackground(new java.awt.Color(214, 5, 5));
        btnAggDept.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAggDept.setForeground(new java.awt.Color(255, 255, 255));
        btnAggDept.setText("Agregar");
        AggDept.add(btnAggDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 90, 30));

        jPanel1.add(AggDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 320));

        AggDirEmp.setBackground(new java.awt.Color(255, 255, 255));
        AggDirEmp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIdDirEmp.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblIdDirEmp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdDirEmp.setText("Id:");
        AggDirEmp.add(lblIdDirEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 30));

        txtIdDirEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtIdDirEmp.setBorder(null);
        AggDirEmp.add(txtIdDirEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 240, 30));
        AggDirEmp.add(jSeparator29, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 260, 10));

        lblCalleDirEmp.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblCalleDirEmp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCalleDirEmp.setText("Calle:");
        AggDirEmp.add(lblCalleDirEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 70, 30));

        txtCalleDirEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCalleDirEmp.setBorder(null);
        AggDirEmp.add(txtCalleDirEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 240, 30));
        AggDirEmp.add(jSeparator30, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 260, 10));

        lblColoniaDirEmp.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblColoniaDirEmp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblColoniaDirEmp.setText("Colonia:");
        AggDirEmp.add(lblColoniaDirEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 80, 30));

        txtColoniaDirEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtColoniaDirEmp.setBorder(null);
        AggDirEmp.add(txtColoniaDirEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 240, 30));
        AggDirEmp.add(jSeparator31, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 260, 10));

        lblNumExtDE.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNumExtDE.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumExtDE.setText("Número Exterior:");
        AggDirEmp.add(lblNumExtDE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 110, 30));

        txtNExtDirEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNExtDirEmp.setBorder(null);
        AggDirEmp.add(txtNExtDirEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 240, 30));
        AggDirEmp.add(jSeparator32, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 260, 10));

        btnAggDirEmp.setBackground(new java.awt.Color(214, 5, 5));
        btnAggDirEmp.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAggDirEmp.setForeground(new java.awt.Color(255, 255, 255));
        btnAggDirEmp.setText("Agregar");
        AggDirEmp.add(btnAggDirEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 90, 30));

        lblMotor4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblMotor4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMotor4.setText("Código Postal:");
        AggDirEmp.add(lblMotor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 110, 30));

        txtCPEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCPEmp.setBorder(null);
        AggDirEmp.add(txtCPEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 240, 30));
        AggDirEmp.add(jSeparator33, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 260, 10));

        jPanel1.add(AggDirEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 320));

        AggCotiz.setBackground(new java.awt.Color(255, 255, 255));
        AggCotiz.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblId5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblId5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblId5.setText("Id de la Cotización:");
        AggCotiz.add(lblId5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 30));

        txtId2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtId2.setBorder(null);
        AggCotiz.add(txtId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 240, 30));
        AggCotiz.add(jSeparator34, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 260, 10));

        lblNombre5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNombre5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre5.setText("Fecha de cotización:");
        AggCotiz.add(lblNombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, 30));

        txtPrecio4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtPrecio4.setBorder(null);
        AggCotiz.add(txtPrecio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 240, 30));
        AggCotiz.add(jSeparator35, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 260, 10));

        lblTrans4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTrans4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTrans4.setText("Nombre del Usuario:");
        AggCotiz.add(lblTrans4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, 30));

        txtTrans4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtTrans4.setBorder(null);
        AggCotiz.add(txtTrans4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 240, 30));
        AggCotiz.add(jSeparator36, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 260, 10));

        lblMotor5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblMotor5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMotor5.setText("Teléfono:");
        AggCotiz.add(lblMotor5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 110, 30));

        txtMotor5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtMotor5.setBorder(null);
        AggCotiz.add(txtMotor5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 240, 30));
        AggCotiz.add(jSeparator37, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 260, 10));

        btnAggCot.setBackground(new java.awt.Color(214, 5, 5));
        btnAggCot.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAggCot.setForeground(new java.awt.Color(255, 255, 255));
        btnAggCot.setText("Agregar");
        AggCotiz.add(btnAggCot, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 90, 30));

        lblMotor6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblMotor6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMotor6.setText("Correo:");
        AggCotiz.add(lblMotor6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 110, 30));

        txtMotor6.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtMotor6.setBorder(null);
        AggCotiz.add(txtMotor6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 240, 30));
        AggCotiz.add(jSeparator38, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 260, 10));

        jPanel1.add(AggCotiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 320));

        AggFacts.setBackground(new java.awt.Color(255, 255, 255));
        AggFacts.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblId6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblId6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblId6.setText("Código de la factura:");
        AggFacts.add(lblId6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 30));

        txtId3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtId3.setBorder(null);
        AggFacts.add(txtId3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 240, 30));
        AggFacts.add(jSeparator39, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 260, 10));

        lblNombre6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNombre6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre6.setText("Método de pago:");
        AggFacts.add(lblNombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, 30));

        txtPrecio5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtPrecio5.setBorder(null);
        AggFacts.add(txtPrecio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 240, 30));
        AggFacts.add(jSeparator40, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 260, 10));

        lblTrans5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTrans5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTrans5.setText("Fecha de venta:");
        AggFacts.add(lblTrans5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, 30));

        txtTrans5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtTrans5.setBorder(null);
        AggFacts.add(txtTrans5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 240, 30));
        AggFacts.add(jSeparator41, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 260, 10));

        btnAggFact.setBackground(new java.awt.Color(214, 5, 5));
        btnAggFact.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAggFact.setForeground(new java.awt.Color(255, 255, 255));
        btnAggFact.setText("Agregar");
        AggFacts.add(btnAggFact, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 90, 30));

        jPanel1.add(AggFacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 320));

        AggCli.setBackground(new java.awt.Color(255, 255, 255));
        AggCli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNumSerie2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNumSerie2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumSerie2.setText("Id del cliente:");
        AggCli.add(lblNumSerie2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 30));

        txtNumSerie2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNumSerie2.setBorder(null);
        AggCli.add(txtNumSerie2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 240, 30));
        AggCli.add(jSeparator42, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 260, 10));

        lblPrecio2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblPrecio2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPrecio2.setText("Nombre:");
        AggCli.add(lblPrecio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, 30));

        txtPrecio6.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtPrecio6.setBorder(null);
        AggCli.add(txtPrecio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 240, 30));
        AggCli.add(jSeparator43, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 260, 10));

        lblPaisP2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblPaisP2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPaisP2.setText("Apellidos:");
        AggCli.add(lblPaisP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 120, 30));

        txtPaisP2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtPaisP2.setBorder(null);
        AggCli.add(txtPaisP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 240, 30));
        AggCli.add(jSeparator44, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 260, 10));

        lblVersion2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblVersion2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVersion2.setText("Sueldo:");
        AggCli.add(lblVersion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 100, 30));

        txtVersion2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtVersion2.setBorder(null);
        AggCli.add(txtVersion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 240, 30));
        AggCli.add(jSeparator45, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 260, 10));

        lblMotor7.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblMotor7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMotor7.setText("RFC:");
        AggCli.add(lblMotor7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 100, 30));

        txtMotor7.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtMotor7.setBorder(null);
        AggCli.add(txtMotor7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 240, 30));
        AggCli.add(jSeparator46, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 260, 10));

        lblTrans6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTrans6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTrans6.setText("Historial Crediticio:");
        AggCli.add(lblTrans6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 110, 30));

        txtTrans6.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtTrans6.setBorder(null);
        AggCli.add(txtTrans6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 240, 30));
        AggCli.add(jSeparator47, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 260, 10));

        lblModelo2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblModelo2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblModelo2.setText("Fecha de registro:");
        AggCli.add(lblModelo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 100, 30));

        txtModelo2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtModelo2.setBorder(null);
        AggCli.add(txtModelo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 120, 30));
        AggCli.add(jSeparator48, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 140, 10));

        lblColor3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblColor3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblColor3.setText("Teléfono:");
        AggCli.add(lblColor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 60, 30));

        txtColor3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtColor3.setBorder(null);
        AggCli.add(txtColor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 140, 30));
        AggCli.add(jSeparator49, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 160, 10));

        btnAggCli.setBackground(new java.awt.Color(214, 5, 5));
        btnAggCli.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAggCli.setForeground(new java.awt.Color(255, 255, 255));
        btnAggCli.setText("Agregar");
        AggCli.add(btnAggCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 90, 30));

        lblColor4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblColor4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblColor4.setText("Correo:");
        AggCli.add(lblColor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 100, 30));

        txtColor4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtColor4.setBorder(null);
        AggCli.add(txtColor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 220, 30));
        AggCli.add(jSeparator50, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 240, 10));

        jPanel1.add(AggCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 320));

        AggDirCli.setBackground(new java.awt.Color(255, 255, 255));
        AggDirCli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblId7.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblId7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblId7.setText("Id:");
        AggDirCli.add(lblId7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 30));

        txtId4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtId4.setBorder(null);
        AggDirCli.add(txtId4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 240, 30));
        AggDirCli.add(jSeparator51, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 260, 10));

        lblNombre7.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNombre7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre7.setText("Calle:");
        AggDirCli.add(lblNombre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 70, 30));

        txtPrecio7.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtPrecio7.setBorder(null);
        AggDirCli.add(txtPrecio7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 240, 30));
        AggDirCli.add(jSeparator52, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 260, 10));

        lblTrans7.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTrans7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTrans7.setText("Colonia:");
        AggDirCli.add(lblTrans7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 80, 30));

        txtTrans7.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtTrans7.setBorder(null);
        AggDirCli.add(txtTrans7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 240, 30));
        AggDirCli.add(jSeparator53, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 260, 10));

        lblMotor8.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblMotor8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMotor8.setText("Número Exterior:");
        AggDirCli.add(lblMotor8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 110, 30));

        txtMotor8.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtMotor8.setBorder(null);
        AggDirCli.add(txtMotor8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 240, 30));
        AggDirCli.add(jSeparator54, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 260, 10));

        btnAggDirCli.setBackground(new java.awt.Color(214, 5, 5));
        btnAggDirCli.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAggDirCli.setForeground(new java.awt.Color(255, 255, 255));
        btnAggDirCli.setText("Agregar");
        AggDirCli.add(btnAggDirCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 90, 30));

        lblMotor9.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblMotor9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMotor9.setText("Código Postal:");
        AggDirCli.add(lblMotor9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 110, 30));

        txtMotor9.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtMotor9.setBorder(null);
        AggDirCli.add(txtMotor9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 240, 30));
        AggDirCli.add(jSeparator55, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 260, 10));

        jPanel1.add(AggDirCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 320));

        lblInstruct.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblInstruct.setForeground(new java.awt.Color(153, 153, 153));
        lblInstruct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstruct.setText("Seleccione una entidad para agregar información:");
        jPanel1.add(lblInstruct, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 320, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void OcultarPanels() {
        AggVcls.setVisible(false);
        AggVrs.setVisible(false);
        AggModelos.setVisible(false);
        AggColors.setVisible(false);
        AggEmp.setVisible(false);
        AggDept.setVisible(false);
        AggDirEmp.setVisible(false);
        AggCotiz.setVisible(false);
        AggFacts.setVisible(false);
        AggCli.setVisible(false);
        AggDirCli.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel AggCli;
    public javax.swing.JPanel AggColors;
    public javax.swing.JPanel AggCotiz;
    public javax.swing.JPanel AggDept;
    public javax.swing.JPanel AggDirCli;
    public javax.swing.JPanel AggDirEmp;
    public javax.swing.JPanel AggEmp;
    public javax.swing.JPanel AggFacts;
    public javax.swing.JPanel AggModelos;
    public javax.swing.JPanel AggVcls;
    public javax.swing.JPanel AggVrs;
    public javax.swing.JButton btnAggCli;
    public javax.swing.JButton btnAggCot;
    public javax.swing.JButton btnAggDept;
    public javax.swing.JButton btnAggDirCli;
    public javax.swing.JButton btnAggDirEmp;
    public javax.swing.JButton btnAggEmp;
    public javax.swing.JButton btnAggFact;
    public javax.swing.JButton btnAgregarClr;
    public javax.swing.JButton btnAgregarMdl;
    public javax.swing.JButton btnAgregarVcl;
    public javax.swing.JButton btnAgregarVrs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator31;
    private javax.swing.JSeparator jSeparator32;
    private javax.swing.JSeparator jSeparator33;
    private javax.swing.JSeparator jSeparator34;
    private javax.swing.JSeparator jSeparator35;
    private javax.swing.JSeparator jSeparator36;
    private javax.swing.JSeparator jSeparator37;
    private javax.swing.JSeparator jSeparator38;
    private javax.swing.JSeparator jSeparator39;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator40;
    private javax.swing.JSeparator jSeparator41;
    private javax.swing.JSeparator jSeparator42;
    private javax.swing.JSeparator jSeparator43;
    private javax.swing.JSeparator jSeparator44;
    private javax.swing.JSeparator jSeparator45;
    private javax.swing.JSeparator jSeparator46;
    private javax.swing.JSeparator jSeparator47;
    private javax.swing.JSeparator jSeparator48;
    private javax.swing.JSeparator jSeparator49;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator50;
    private javax.swing.JSeparator jSeparator51;
    private javax.swing.JSeparator jSeparator52;
    private javax.swing.JSeparator jSeparator53;
    private javax.swing.JSeparator jSeparator54;
    private javax.swing.JSeparator jSeparator55;
    private javax.swing.JSeparator jSeparator56;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblAccion;
    private javax.swing.JLabel lblApellEmp;
    private javax.swing.JLabel lblCalleDirEmp;
    private javax.swing.JLabel lblColoniaDirEmp;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblColor1;
    private javax.swing.JLabel lblColor2;
    private javax.swing.JLabel lblColor3;
    private javax.swing.JLabel lblColor4;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblId5;
    private javax.swing.JLabel lblId6;
    private javax.swing.JLabel lblId7;
    private javax.swing.JLabel lblIdClr;
    private javax.swing.JLabel lblIdDept;
    private javax.swing.JLabel lblIdDirEmp;
    private javax.swing.JLabel lblIdEmp;
    private javax.swing.JLabel lblIdMdl;
    private javax.swing.JLabel lblInstruct;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblModelo1;
    private javax.swing.JLabel lblModelo2;
    private javax.swing.JLabel lblMotor2;
    private javax.swing.JLabel lblMotor4;
    private javax.swing.JLabel lblMotor5;
    private javax.swing.JLabel lblMotor6;
    private javax.swing.JLabel lblMotor7;
    private javax.swing.JLabel lblMotor8;
    private javax.swing.JLabel lblMotor9;
    private javax.swing.JLabel lblMotorMt;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre5;
    private javax.swing.JLabel lblNombre6;
    private javax.swing.JLabel lblNombre7;
    private javax.swing.JLabel lblNombreClr;
    private javax.swing.JLabel lblNombreDept;
    private javax.swing.JLabel lblNombreEmp;
    private javax.swing.JLabel lblNombreMdl;
    private javax.swing.JLabel lblNumExtDE;
    private javax.swing.JLabel lblNumSerie;
    private javax.swing.JLabel lblNumSerie2;
    private javax.swing.JLabel lblPaisP;
    private javax.swing.JLabel lblPaisP2;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPrecio2;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTrans2;
    private javax.swing.JLabel lblTrans4;
    private javax.swing.JLabel lblTrans5;
    private javax.swing.JLabel lblTrans6;
    private javax.swing.JLabel lblTrans7;
    private javax.swing.JLabel lblTransmision;
    private javax.swing.JLabel lblVersion;
    private javax.swing.JLabel lblVersion1;
    private javax.swing.JLabel lblVersion2;
    public javax.swing.JComboBox<String> listaEntidades;
    public javax.swing.JTextField txtApellEmp;
    public javax.swing.JTextField txtCPEmp;
    public javax.swing.JTextField txtCalleDirEmp;
    public javax.swing.JTextField txtColoniaDirEmp;
    public javax.swing.JTextField txtColor;
    public javax.swing.JTextField txtColor3;
    public javax.swing.JTextField txtColor4;
    public javax.swing.JTextField txtComiEmp;
    public javax.swing.JTextField txtContrEmp;
    public javax.swing.JTextField txtCorreoEmp;
    public javax.swing.JTextField txtId;
    public javax.swing.JTextField txtId2;
    public javax.swing.JTextField txtId3;
    public javax.swing.JTextField txtId4;
    public javax.swing.JTextField txtIdColor;
    public javax.swing.JTextField txtIdDept;
    public javax.swing.JTextField txtIdDirEmp;
    public javax.swing.JTextField txtIdEmp;
    public javax.swing.JTextField txtIdModelo;
    public javax.swing.JTextField txtModelo;
    public javax.swing.JTextField txtModelo2;
    public javax.swing.JTextField txtMotor5;
    public javax.swing.JTextField txtMotor6;
    public javax.swing.JTextField txtMotor7;
    public javax.swing.JTextField txtMotor8;
    public javax.swing.JTextField txtMotor9;
    public javax.swing.JTextField txtMotorMt;
    public javax.swing.JTextField txtNExtDirEmp;
    public javax.swing.JTextField txtNSSEmp;
    public javax.swing.JTextField txtNombreClr;
    public javax.swing.JTextField txtNombreDept;
    public javax.swing.JTextField txtNombreEmp;
    public javax.swing.JTextField txtNombreMod;
    public javax.swing.JTextField txtNombreVrs;
    public javax.swing.JTextField txtNumSerie;
    public javax.swing.JTextField txtNumSerie2;
    public javax.swing.JTextField txtPaisP;
    public javax.swing.JTextField txtPaisP2;
    public javax.swing.JTextField txtPrecio;
    public javax.swing.JTextField txtPrecio4;
    public javax.swing.JTextField txtPrecio5;
    public javax.swing.JTextField txtPrecio6;
    public javax.swing.JTextField txtPrecio7;
    public javax.swing.JTextField txtStock;
    public javax.swing.JTextField txtTelefEmp;
    public javax.swing.JTextField txtTrans4;
    public javax.swing.JTextField txtTrans5;
    public javax.swing.JTextField txtTrans6;
    public javax.swing.JTextField txtTrans7;
    public javax.swing.JTextField txtTransmision;
    public javax.swing.JTextField txtUserEmp;
    public javax.swing.JTextField txtVersion;
    public javax.swing.JTextField txtVersion2;
    // End of variables declaration//GEN-END:variables
}
